details:
- algorithm:
    aligner: false
    effects: vep
    effects_transcripts: all
    ensemble:
      numpass: 1
      use_filtered: false
    mark_duplicates: false
    realign: false
    recalibrate: false
    save_diskspace: true
    tools_off:
    - gatk4
    tools_on:
    - gemini
    - svplots
    - qualimap
    - vep_splicesite_annotations
    - noalt_calling
    variantcaller: false
    vcfanno:
    - /home/teja/cre/cre.vcfanno.conf
  analysis: variant2
  description: [familyid]_sample
  vrn_file: ../input/[vrn_file]
  genome_build: GRCh37
  metadata:
    batch: [familyid]
resources:
  default:
    cores: 7
    jvm_opts:
    - -Xms750m
    - -Xmx7000m
    memory: 7G
upload:
  dir: ../final
