details:
- algorithm:
    aligner: false
    bam_clean: remove_extracontigs
    effects: vep
    effects_transcripts: all
    ensemble:
      numpass: 2
      use_filtered: false
    realign: false
    recalibrate: false
    mark_duplicates: false
    save_diskspace: true
    tools_on:
    - gemini
    - svplots
    - qualimap
    - vep_splicesite_annotations
    - noalt_calling
    tools_off:
    - gatk4
    variantcaller:
    - gatk-haplotype
    - platypus
    - freebayes
    - samtools
    vcfanno:
    - /home/teja/cre/cre.vcfanno.conf
  analysis: variant2
  description: 'project_sample'
  files:
  - /hpf/largeprojects/ccmbio/naumenko/project_cheo/912R/input/912R_A337376.bam
  genome_build: GRCh37
  metadata:
    batch: 912R
resources:
  default:
    cores: 7
    jvm_opts:
    - -Xms750m
    - -Xmx7000m
    memory: 7G
upload:
  dir: ../final
